apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: omega
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: omega
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: omega
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: omega123
            - name: MONGO_INITDB_DATABASE
              value: omega
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
